[project]
name = "add-vent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.0.2",
    "pyspark>=3.5.5",
    "spark-nlp>=6.0.0",
]
